version: "3.9"

services:
  trust-registry:
    image: trust-registry:local
    build:
      context: .
      dockerfile: trust-registry/Dockerfile
    env_file:
      - .env.test
    environment:
      LISTEN_ADDRESS: 0.0.0.0:3232
      FILE_STORAGE_PATH: /usr/local/bin/sample-data/data.csv
    ports:
      - "3232:3232"
    volumes:
      - ./didcomm-server/tests/tmp:/tmp
