version: "3.9"

services:
  didcomm-server:
    image: trust-registry-didcomm:local
    build:
      context: .
      dockerfile: didcomm-server/Dockerfile
    env_file:
      - .env.test
    environment:
      LISTEN_ADDRESS: 0.0.0.0:3131
      FILE_STORAGE_PATH: ./didcomm-server/tests/tmp/data.csv
    ports:
      - "3131:3131"
    volumes:
      - ./didcomm-server/tests/tmp:/tmp
