version: "3.9"

services:
  trust-registry:
    platform: linux/arm64
    image: trust-registry:local
    build:
      context: .
      dockerfile: trust-registry/Dockerfile
      platforms:
        - linux/arm64
    env_file:
      - .env
    environment:
      LISTEN_ADDRESS: 0.0.0.0:3232
      FILE_STORAGE_PATH: /sample-data/data.csv
    ports:
      - "3232:3232"
    volumes:
      - ./sample-data:/sample-data
  localstack:
    image: localstack/localstack:3.6.0
    container_name: localstack
    restart: always
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb,firehose,kms,secretsmanager,sqs,events,s3,eventbridge,iot
      - DEBUG=1
      - DEFAULT_REGION=ap-southeast-1
