name: checks

on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  rust-pipeline:
    uses: affinidi/pipeline-rust/.github/workflows/checks.yaml@FTL-24205
    secrets: inherit
    with:
      toolchain: '1.88.0'
      rustflags: ' --cfg tracing_unstable'
      auditIgnore: 'RUSTSEC-2022-0040,RUSTSEC-2023-0071,RUSTSEC-2024-0373'
      coverage: 45
      useRedis: false
      doNotInherit: 'test,coverage'
