on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions-rust-lang/audit@v1
        name: Audit Rust Dependencies
        with:
          file: audit.toml
  cargo-deny:
    name: 'License check'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          rust-version: '1.85.0'
          command: check bans licenses sources
  check:
    name: Cargo Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ''
          toolchain: stable
          override: true
      - uses: affinidi/pipeline-rust/.github/actions/rust-dependencies@main
      - run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ''
          toolchain: stable
          override: true
      - uses: affinidi/pipeline-rust/.github/actions/rust-dependencies@main
      - run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ''
          toolchain: stable
          override: true
          components: rustfmt
      - uses: affinidi/pipeline-rust/.github/actions/rust-dependencies@main
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  clippy:
    name: Clippy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ''
          toolchain: stable
          override: true
          components: clippy
      - uses: affinidi/pipeline-rust/.github/actions/rust-dependencies@main
      - run: cargo clippy --no-deps

  coverage:
    name: Coverage
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ''
          toolchain: stable
          override: true
      - uses: affinidi/pipeline-rust/.github/actions/rust-dependencies@main
      - name: Generate code coverage
        run: |
          if ! cargo llvm-cov --version; then
            cargo install cargo-llvm-cov
          fi

          for crate_name in $(cargo metadata --format-version=1 --no-deps | jq -r '.packages[] | select(.source == null) | .name'); do
            echo "Generating coverage for crate at $crate_name"

            local_version=$(cargo info ${crate_name} | grep "version" | grep --invert-match "rust-version" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
            cargo llvm-cov --package ${crate_name}@${local_version} --summary-only --fail-under-lines=70
          done
